[package]
name = "spyrodecimal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boiler_plate = { path = "../boiler_plate" }
rand = "0.8.4"
